spring.application.name=expense-splitter

spring.datasource.url=jdbc:postgresql://localhost:5432/expense_splitter
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=expense_splitter
spring.jpa.open-in-view=false

spring.datasource.hikari.pool-name=ExpenseSplitterPool
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000